# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2de938f5-c353-4e97-996d-de1fe110a8e4";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0D67-4C0C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # ===== CUSTOM CONFIGURATIONS =====

  boot.consoleLogLevel = 3;
  # boot.kernelParams = [ "libata.force=pio4,noncq" "libata.noacpi=1" "ahci.mobile_lpm_policy=1" ];

  # fileSystems."/mnt/data" = {
  #   device = "/dev/disk/by-uuid/ec99be68-d52b-4d88-aed6-dec9abf4ad4b";
  #   fsType = "ext4";
  #   options = [ "defaults" "noatime" "nofail" ];
  # };

}
